#spark parameters
appName: "Partition Metrics"
defaultKeyspace: "default keyspace"
outputTable: "partition_metrics"
outputKeyspace: "output keyspace"
minPartSize: 104857600

sparkConfigs:
    spark.cores.max: "200"
    spark.executor.memory: "8G"
    spark.serializer: "org.apache.spark.serializer.KryoSerializer"
    spark.cassandra.connection.host: "127.0.0.1"
    spark.cassandra.auth.username: "user name"
    spark.cassandra.auth.password: "password"
    #spark.cassandra.connection.local_dc: "dc name" --use if there are multiple Data Centers
    spark.cassandra.connection.keep_alive_ms: "180000"
    spark.cassandra.input.consistency.level: "LOCAL_QUORUM"
    spark.cassandra.output.consistency.level: "LOCAL_QUORUM"
    spark.executor.extraJavaOptions: "-XX:+UseG1GC -XX:MaxGCPauseMillis=150 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1ReservePercent=20 -XX:+UseStringDeduplication"
    spark.driver.extraJavaOptions: "-XX:+UseG1GC -XX:MaxGCPauseMillis=150 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1ReservePercent=20 -XX:+UseStringDeduplication"
    spark.cassandra.query.retry.count: "5"
    spark.cassandra.read.timeout_ms: "5000"
    spark.io.compression.codec: "org.apache.spark.io.LZ4CompressionCodec"
    spark.rdd.compress: "true"
    spark.task.maxFailures: "2"
    spark.akka.frameSize: "100"
